name: whatsapp-api-8193
services:
  whatsapp-api:
    build:
      context: .
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: 8193
    ports:
      - "8193:8193"
    volumes:
      - ./data-8193:/app/data
    restart: always
